# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTemplateProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for SwiftTemplateProject
  pod 'Capable'
  pod 'CocoaDebug', :configurations => ['Debug']
  pod 'DateToolsSwift'
  pod "ESTabBarController-swift"  #tabbar导航 https://github.com/HansongSwiftProject/ESTabBarControlle
  pod 'EasySwiftHook'
  pod 'Instabug' # https://dashboard.instabug.com/welcome-to-instabug
  pod 'NotificationBannerSwift'
  pod 'R.swift' #https://github.com/mac-cain13/R.swift
  pod 'R.swift.Library'#https://github.com/mac-cain13/R.swift.Library
  pod 'RxSwift'  #RxSwift  https://beeth0ven.github.io/RxSwift-Chinese-Documentation/content/decision_tree.html
  pod 'RxCocoa'  #RxCocca
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '6.0.4'
  pod 'SheetyColors'
  
  pod 'SwiftDate'
  
  pod 'SwiftGen'
  pod 'SwiftGifOrigin'
  
  pod 'SwiftHook'
  
  pod 'SwiftKeychainWrapper'
  
  pod 'SwiftLint'
  
  pod 'SwiftMath'
  pod 'SwiftMesh'
  pod 'SwiftMessages'
  
  pod "SwiftSpinner"
  
  pod 'Swinject'
#  pod 'SwinjectStoryboard'
  
#  pod 'SwiftValidator'
  
  pod 'SwiftyBeaver'
  pod 'SwiftyUserDefaults'
  pod 'SwiftyTimer'
  
  pod 'SwipeCellKit'
  pod 'SWXMLHash'
#  pod 'UITestHelper'#https://github.com/evermeer/UITestHelper
  target 'SwiftTemplateProjectTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking' #https://cocoapods.org/pods/RxBlocking
    pod 'RxTest'
  end

  target 'SwiftTemplateProjectUITests' do
    # Pods for testing
  end

end
